// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LaffOutLoud
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int translucent = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int translucent_black = 2130968576;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accessorybox = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int adressbook = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int alertbottomback = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int alertheaderback = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int animationsettings = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int attachmentspreviewbkgr = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int audiofile = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int audiofilelarge = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int back = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int barndoors = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int blinds = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bottompencil = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int brush = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btnblue = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btnblueback = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btngrayback = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bubbleleft = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bubbleright = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bubblesolidleft = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bubblesolidright = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int button = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int buttonGrey = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int checkbox = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int @checked = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int colorpalette = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int colorPickerBox1 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int colorPickerBox10 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int colorPickerBox11 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int colorPickerBox12 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int colorPickerBox2 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int colorPickerBox3 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int colorPickerBox4 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int colorPickerBox5 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int colorPickerBox6 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int colorPickerBox7 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int colorPickerBox8 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int colorPickerBox9 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int comicmsgs = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int comiconmsg = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int comiconmsglarge = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int comicons = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int comiconsnobkgr = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int comixmsg = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int comixmsglarge = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int comixnobkgr = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int contacts = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int cut = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int defaultuserimage = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int delete = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int drawicon = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int drawmsg = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int drawmsglarge = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int emoticonmsg = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int emoticonmsglarge = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int emoticons = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int emptycircle = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int fade = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int fadethroughblack = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int fbfriends = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int final9patch = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int flip = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int fold = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int footerback = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int glow = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int googlefriends = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int gradientblue = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int gradientgreen = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int gradientred = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int gradientwhite = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int gradientwipe = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int headerback = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int headerlogo = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int home = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int icoadd = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int icoanimation = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int icoback = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int icocheckbox = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int icochecked = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int icocircleempty = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int icocirclemarked = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int icocomicons = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int icocomix = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int icoemoticons = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int icofacebook = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int icogoogle = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int icohome = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int icolinkedin = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int icolol = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int icomic = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int Icon = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int icoplayback = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int icoplaybackred = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int icopolls = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int icoreply = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int icosoundfx = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int icotext = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int icotwitter = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int icoundo = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int icovideo = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int icovoice = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int icoyellowcamera = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int icoyoutube = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int LinkedInFriends = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int markedcircle = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int messagelist = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int microphone = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int musicfile = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int newuserphoto = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int nobkgrcamera = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int nocamera = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int nocamera2 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int nomicrophone = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int nomicrophone2 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int novideo = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int pausebutton = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int pencil = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int picmsg = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int picture = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int playblack = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int playbutton = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int pollmsg = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int pollmsglarge = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int polls = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int radialwipe = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int randombars = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int randomdissolve = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int recordvoice = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int redarrow = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int reply = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int rotateleftbottom = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int rotatelefttop = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int rotaterightbottom = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int rotaterighttop = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int rubberstamp = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int save = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int selectorbar = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int settings = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int slidebottomleft = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int slideleft = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int slideright = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int slidetopright = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int smallcallout = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int smalltrashbin = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int soundfxmsg = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int splashscreen = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int stopbutton = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int switchcamera = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int textbackground = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int textfieldback = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int textfieldsolidlarge = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int textmsg = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int textmsgicon = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int textmsglarge = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int textmsgnobkgr = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int textwrite = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int trashbin = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int undo = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int userbkgr = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int userbkgr2 = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int userbkgrtransparent = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int usercutout = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int video = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int videomsg = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int videomsglarge = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int voicemsg = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int voicemsglarge = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int wheel = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int yellowempty = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int youtubefriends = 2130837674;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07009f
			public const int GetConnectedFacebook = 2131165343;
			
			// aapt resource value: 0x7f0700a2
			public const int GetConnectedGoogle = 2131165346;
			
			// aapt resource value: 0x7f070052
			public const int arrow1 = 2131165266;
			
			// aapt resource value: 0x7f070056
			public const int arrow2 = 2131165270;
			
			// aapt resource value: 0x7f07005d
			public const int arrow3 = 2131165277;
			
			// aapt resource value: 0x7f070061
			public const int arrow4 = 2131165281;
			
			// aapt resource value: 0x7f07003b
			public const int btnAdd = 2131165243;
			
			// aapt resource value: 0x7f070072
			public const int btnAddContent = 2131165298;
			
			// aapt resource value: 0x7f0700ab
			public const int btnAddressBook = 2131165355;
			
			// aapt resource value: 0x7f070107
			public const int btnAnimate = 2131165447;
			
			// aapt resource value: 0x7f07002b
			public const int btnBack = 2131165227;
			
			// aapt resource value: 0x7f07008f
			public const int btnBlockUser = 2131165327;
			
			// aapt resource value: 0x7f07001f
			public const int btnCamera = 2131165215;
			
			// aapt resource value: 0x7f0700ba
			public const int btnCancel = 2131165370;
			
			// aapt resource value: 0x7f0700c5
			public const int btnChoosePic = 2131165381;
			
			// aapt resource value: 0x7f0700f3
			public const int btnCloseVideo = 2131165427;
			
			// aapt resource value: 0x7f070046
			public const int btnComiconMessage = 2131165254;
			
			// aapt resource value: 0x7f070044
			public const int btnComixMessage = 2131165252;
			
			// aapt resource value: 0x7f070108
			public const int btnContacts = 2131165448;
			
			// aapt resource value: 0x7f07003a
			public const int btnCreateAnimation = 2131165242;
			
			// aapt resource value: 0x7f07007d
			public const int btnCreateButton = 2131165309;
			
			// aapt resource value: 0x7f07006d
			public const int btnCreatePhotoPoll = 2131165293;
			
			// aapt resource value: 0x7f070090
			public const int btnDeleteUser = 2131165328;
			
			// aapt resource value: 0x7f070041
			public const int btnDone = 2131165249;
			
			// aapt resource value: 0x7f070043
			public const int btnDrawMessage = 2131165251;
			
			// aapt resource value: 0x7f07004a
			public const int btnEmotMessage = 2131165258;
			
			// aapt resource value: 0x7f0700ca
			public const int btnFindContact = 2131165386;
			
			// aapt resource value: 0x7f0700bf
			public const int btnForgotPassword = 2131165375;
			
			// aapt resource value: 0x7f070020
			public const int btnGetConnectedContinue = 2131165216;
			
			// aapt resource value: 0x7f07003d
			public const int btnHome = 2131165245;
			
			// aapt resource value: 0x7f0700be
			public const int btnLogin = 2131165374;
			
			// aapt resource value: 0x7f0700ad
			public const int btnLogout = 2131165357;
			
			// aapt resource value: 0x7f0700ac
			public const int btnMessageList = 2131165356;
			
			// aapt resource value: 0x7f070073
			public const int btnMessageSend = 2131165299;
			
			// aapt resource value: 0x7f07009a
			public const int btnOnline = 2131165338;
			
			// aapt resource value: 0x7f0700e4
			public const int btnOpt1 = 2131165412;
			
			// aapt resource value: 0x7f0700e6
			public const int btnOpt2 = 2131165414;
			
			// aapt resource value: 0x7f0700e8
			public const int btnOpt3 = 2131165416;
			
			// aapt resource value: 0x7f0700ea
			public const int btnOpt4 = 2131165418;
			
			// aapt resource value: 0x7f0700da
			public const int btnOption1 = 2131165402;
			
			// aapt resource value: 0x7f0700dc
			public const int btnOption2 = 2131165404;
			
			// aapt resource value: 0x7f0700de
			public const int btnOption3 = 2131165406;
			
			// aapt resource value: 0x7f0700e0
			public const int btnOption4 = 2131165408;
			
			// aapt resource value: 0x7f070104
			public const int btnPause = 2131165444;
			
			// aapt resource value: 0x7f070040
			public const int btnPlay = 2131165248;
			
			// aapt resource value: 0x7f070047
			public const int btnPollMessage = 2131165255;
			
			// aapt resource value: 0x7f07003e
			public const int btnRecord = 2131165246;
			
			// aapt resource value: 0x7f0700c7
			public const int btnRegister = 2131165383;
			
			// aapt resource value: 0x7f0700b9
			public const int btnReset = 2131165369;
			
			// aapt resource value: 0x7f070049
			public const int btnSFXMessage = 2131165257;
			
			// aapt resource value: 0x7f070099
			public const int btnSearch = 2131165337;
			
			// aapt resource value: 0x7f07003c
			public const int btnSend = 2131165244;
			
			// aapt resource value: 0x7f070105
			public const int btnStop = 2131165445;
			
			// aapt resource value: 0x7f070106
			public const int btnSwitchCamera = 2131165446;
			
			// aapt resource value: 0x7f0700c6
			public const int btnTakePic = 2131165382;
			
			// aapt resource value: 0x7f070042
			public const int btnTextMessage = 2131165250;
			
			// aapt resource value: 0x7f070091
			public const int btnUniBack = 2131165329;
			
			// aapt resource value: 0x7f0700e3
			public const int btnUniHome = 2131165411;
			
			// aapt resource value: 0x7f070092
			public const int btnUniSettings = 2131165330;
			
			// aapt resource value: 0x7f070048
			public const int btnVideoMessage = 2131165256;
			
			// aapt resource value: 0x7f070045
			public const int btnVoiceMessage = 2131165253;
			
			// aapt resource value: 0x7f0700b7
			public const int btnloginexistingUser = 2131165367;
			
			// aapt resource value: 0x7f0700b6
			public const int btnloginnewUser = 2131165366;
			
			// aapt resource value: 0x7f0700e2
			public const int button2 = 2131165410;
			
			// aapt resource value: 0x7f070085
			public const int content = 2131165317;
			
			// aapt resource value: 0x7f07008c
			public const int customView = 2131165324;
			
			// aapt resource value: 0x7f0700ae
			public const int dialogText = 2131165358;
			
			// aapt resource value: 0x7f070084
			public const int drawingArea = 2131165316;
			
			// aapt resource value: 0x7f0700c2
			public const int editCode = 2131165378;
			
			// aapt resource value: 0x7f0700b8
			public const int editEmail = 2131165368;
			
			// aapt resource value: 0x7f070097
			public const int editEmailAddress = 2131165335;
			
			// aapt resource value: 0x7f070095
			public const int editFirstName = 2131165333;
			
			// aapt resource value: 0x7f070096
			public const int editLastName = 2131165334;
			
			// aapt resource value: 0x7f0700bd
			public const int editPassword = 2131165373;
			
			// aapt resource value: 0x7f0700c3
			public const int editPasswordVerify = 2131165379;
			
			// aapt resource value: 0x7f070098
			public const int editPhoneNumber = 2131165336;
			
			// aapt resource value: 0x7f0700a8
			public const int editSearch = 2131165352;
			
			// aapt resource value: 0x7f0700c0
			public const int editText1 = 2131165376;
			
			// aapt resource value: 0x7f070070
			public const int editTextMessage = 2131165296;
			
			// aapt resource value: 0x7f07004b
			public const int gridView1 = 2131165259;
			
			// aapt resource value: 0x7f070086
			public const int handle = 2131165318;
			
			// aapt resource value: 0x7f07000d
			public const int horizontalScrollView1 = 2131165197;
			
			// aapt resource value: 0x7f0700c4
			public const int imageView1 = 2131165380;
			
			// aapt resource value: 0x7f0700ec
			public const int imageView2 = 2131165420;
			
			// aapt resource value: 0x7f0700ed
			public const int imageView3 = 2131165421;
			
			// aapt resource value: 0x7f0700ee
			public const int imageView4 = 2131165422;
			
			// aapt resource value: 0x7f0700ef
			public const int imageView5 = 2131165423;
			
			// aapt resource value: 0x7f070018
			public const int imgAdd = 2131165208;
			
			// aapt resource value: 0x7f070030
			public const int imgColour = 2131165232;
			
			// aapt resource value: 0x7f070032
			public const int imgComicon = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int imgComix = 2131165235;
			
			// aapt resource value: 0x7f07008a
			public const int imgConfig = 2131165322;
			
			// aapt resource value: 0x7f07008d
			public const int imgContactPic = 2131165325;
			
			// aapt resource value: 0x7f070036
			public const int imgCut = 2131165238;
			
			// aapt resource value: 0x7f070034
			public const int imgEmoticon = 2131165236;
			
			// aapt resource value: 0x7f07009e
			public const int imgGetConnectedFacebook = 2131165342;
			
			// aapt resource value: 0x7f0700a1
			public const int imgGetConnectedGoogleFriends = 2131165345;
			
			// aapt resource value: 0x7f07009b
			public const int imgGetConnectedHeader = 2131165339;
			
			// aapt resource value: 0x7f0700a4
			public const int imgGetConnectedLinkedIn = 2131165348;
			
			// aapt resource value: 0x7f070002
			public const int imgHeader = 2131165186;
			
			// aapt resource value: 0x7f07008b
			public const int imgHome = 2131165323;
			
			// aapt resource value: 0x7f0700cc
			public const int imgItemPic = 2131165388;
			
			// aapt resource value: 0x7f0700b2
			public const int imgLinkedIn = 2131165362;
			
			// aapt resource value: 0x7f070003
			public const int imgNewLoginHeader = 2131165187;
			
			// aapt resource value: 0x7f0700b0
			public const int imgNewUserFacebook = 2131165360;
			
			// aapt resource value: 0x7f0700af
			public const int imgNewUserGoogle = 2131165359;
			
			// aapt resource value: 0x7f07001d
			public const int imgNewUserHeader = 2131165213;
			
			// aapt resource value: 0x7f0700b3
			public const int imgNewUserLOL = 2131165363;
			
			// aapt resource value: 0x7f0700b1
			public const int imgNewUsertwitter = 2131165361;
			
			// aapt resource value: 0x7f070038
			public const int imgNewloginHeader = 2131165240;
			
			// aapt resource value: 0x7f07002a
			public const int imgOpacity = 2131165226;
			
			// aapt resource value: 0x7f07002f
			public const int imgPaint = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int imgPencil = 2131165233;
			
			// aapt resource value: 0x7f07006e
			public const int imgPhotoPoll = 2131165294;
			
			// aapt resource value: 0x7f070089
			public const int imgPicture = 2131165321;
			
			// aapt resource value: 0x7f070065
			public const int imgPlay = 2131165285;
			
			// aapt resource value: 0x7f0700cf
			public const int imgPoll1 = 2131165391;
			
			// aapt resource value: 0x7f0700d0
			public const int imgPoll2 = 2131165392;
			
			// aapt resource value: 0x7f0700d3
			public const int imgPoll3 = 2131165395;
			
			// aapt resource value: 0x7f0700d4
			public const int imgPoll4 = 2131165396;
			
			// aapt resource value: 0x7f070069
			public const int imgPollPhoto1 = 2131165289;
			
			// aapt resource value: 0x7f07006a
			public const int imgPollPhoto2 = 2131165290;
			
			// aapt resource value: 0x7f07006b
			public const int imgPollPhoto3 = 2131165291;
			
			// aapt resource value: 0x7f07006c
			public const int imgPollPhoto4 = 2131165292;
			
			// aapt resource value: 0x7f07004c
			public const int imgProfilePic = 2131165260;
			
			// aapt resource value: 0x7f070029
			public const int imgRGB = 2131165225;
			
			// aapt resource value: 0x7f070067
			public const int imgRecordPollMsg = 2131165287;
			
			// aapt resource value: 0x7f070019
			public const int imgRemove = 2131165209;
			
			// aapt resource value: 0x7f07002e
			public const int imgSave = 2131165230;
			
			// aapt resource value: 0x7f070088
			public const int imgSound = 2131165320;
			
			// aapt resource value: 0x7f07002d
			public const int imgStamp = 2131165229;
			
			// aapt resource value: 0x7f070051
			public const int imgStep1 = 2131165265;
			
			// aapt resource value: 0x7f070050
			public const int imgStep1Back = 2131165264;
			
			// aapt resource value: 0x7f070055
			public const int imgStep2 = 2131165269;
			
			// aapt resource value: 0x7f070054
			public const int imgStep2Back = 2131165268;
			
			// aapt resource value: 0x7f070059
			public const int imgStep3 = 2131165273;
			
			// aapt resource value: 0x7f070058
			public const int imgStep3Back = 2131165272;
			
			// aapt resource value: 0x7f07005c
			public const int imgStep4 = 2131165276;
			
			// aapt resource value: 0x7f07005b
			public const int imgStep4Back = 2131165275;
			
			// aapt resource value: 0x7f070060
			public const int imgStep5 = 2131165280;
			
			// aapt resource value: 0x7f07005f
			public const int imgStep5Back = 2131165279;
			
			// aapt resource value: 0x7f070064
			public const int imgStep6 = 2131165284;
			
			// aapt resource value: 0x7f070063
			public const int imgStep6Back = 2131165283;
			
			// aapt resource value: 0x7f070035
			public const int imgText = 2131165237;
			
			// aapt resource value: 0x7f07006f
			public const int imgTextPoll = 2131165295;
			
			// aapt resource value: 0x7f07002c
			public const int imgUndo = 2131165228;
			
			// aapt resource value: 0x7f07001c
			public const int imgView1 = 2131165212;
			
			// aapt resource value: 0x7f070037
			public const int imgVoice = 2131165239;
			
			// aapt resource value: 0x7f0700db
			public const int imgVote1 = 2131165403;
			
			// aapt resource value: 0x7f0700dd
			public const int imgVote2 = 2131165405;
			
			// aapt resource value: 0x7f0700df
			public const int imgVote3 = 2131165407;
			
			// aapt resource value: 0x7f0700e1
			public const int imgVote4 = 2131165409;
			
			// aapt resource value: 0x7f0700b4
			public const int imgYouTube = 2131165364;
			
			// aapt resource value: 0x7f0700d8
			public const int linearHolder = 2131165400;
			
			// aapt resource value: 0x7f070100
			public const int linearLay10 = 2131165440;
			
			// aapt resource value: 0x7f070101
			public const int linearLay11 = 2131165441;
			
			// aapt resource value: 0x7f0700f9
			public const int linearLay12 = 2131165433;
			
			// aapt resource value: 0x7f0700fa
			public const int linearLay13 = 2131165434;
			
			// aapt resource value: 0x7f0700fb
			public const int linearLay14 = 2131165435;
			
			// aapt resource value: 0x7f0700fc
			public const int linearLay15 = 2131165436;
			
			// aapt resource value: 0x7f0700f4
			public const int linearLay2 = 2131165428;
			
			// aapt resource value: 0x7f0700f5
			public const int linearLay3 = 2131165429;
			
			// aapt resource value: 0x7f0700f6
			public const int linearLay4 = 2131165430;
			
			// aapt resource value: 0x7f0700f7
			public const int linearLay5 = 2131165431;
			
			// aapt resource value: 0x7f0700f8
			public const int linearLay6 = 2131165432;
			
			// aapt resource value: 0x7f0700fd
			public const int linearLay7 = 2131165437;
			
			// aapt resource value: 0x7f0700fe
			public const int linearLay8 = 2131165438;
			
			// aapt resource value: 0x7f0700ff
			public const int linearLay9 = 2131165439;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout10 = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout11 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout12 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int linearLayout13 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout14 = 2131165205;
			
			// aapt resource value: 0x7f0700f1
			public const int linearLayout15 = 2131165425;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout2 = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout3 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout4 = 2131165192;
			
			// aapt resource value: 0x7f0700d7
			public const int linearLayout44 = 2131165399;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout5 = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int linearLayout6 = 2131165210;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout7 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int linearLayout8 = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout9 = 2131165198;
			
			// aapt resource value: 0x7f070039
			public const int linearLayoutwrap = 2131165241;
			
			// aapt resource value: 0x7f0700a6
			public const int linearListContainer = 2131165350;
			
			// aapt resource value: 0x7f070083
			public const int linearListWrapper = 2131165315;
			
			// aapt resource value: 0x7f070094
			public const int linearResultsWrapper = 2131165332;
			
			// aapt resource value: 0x7f070081
			public const int listContentPack = 2131165313;
			
			// aapt resource value: 0x7f0700aa
			public const int messageBlock = 2131165354;
			
			// aapt resource value: 0x7f0700a9
			public const int msgScrollKeeper = 2131165353;
			
			// aapt resource value: 0x7f07009c
			public const int newGetConnectedImage = 2131165340;
			
			// aapt resource value: 0x7f0700e5
			public const int pbRes1 = 2131165413;
			
			// aapt resource value: 0x7f0700e7
			public const int pbRes2 = 2131165415;
			
			// aapt resource value: 0x7f0700e9
			public const int pbRes3 = 2131165417;
			
			// aapt resource value: 0x7f0700eb
			public const int pbRes4 = 2131165419;
			
			// aapt resource value: 0x7f0700d5
			public const int pbVoteBL = 2131165397;
			
			// aapt resource value: 0x7f0700d6
			public const int pbVoteBR = 2131165398;
			
			// aapt resource value: 0x7f0700d1
			public const int pbVoteTL = 2131165393;
			
			// aapt resource value: 0x7f0700d2
			public const int pbVoteTR = 2131165394;
			
			// aapt resource value: 0x7f0700d9
			public const int prgPreview = 2131165401;
			
			// aapt resource value: 0x7f07003f
			public const int progressBar1 = 2131165247;
			
			// aapt resource value: 0x7f07004f
			public const int relImage1 = 2131165263;
			
			// aapt resource value: 0x7f070053
			public const int relImage2 = 2131165267;
			
			// aapt resource value: 0x7f070057
			public const int relImage3 = 2131165271;
			
			// aapt resource value: 0x7f07005a
			public const int relImage4 = 2131165274;
			
			// aapt resource value: 0x7f07005e
			public const int relImage5 = 2131165278;
			
			// aapt resource value: 0x7f070062
			public const int relImage6 = 2131165282;
			
			// aapt resource value: 0x7f07009d
			public const int relLayoutFacebookFriends = 2131165341;
			
			// aapt resource value: 0x7f0700a0
			public const int relLayoutGoogleFriends = 2131165344;
			
			// aapt resource value: 0x7f0700a3
			public const int relLayoutLinkedIn = 2131165347;
			
			// aapt resource value: 0x7f070001
			public const int relativeLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070071
			public const int relativeLayout2 = 2131165297;
			
			// aapt resource value: 0x7f070093
			public const int scrollResultsWrapper = 2131165331;
			
			// aapt resource value: 0x7f070080
			public const int scrollView1 = 2131165312;
			
			// aapt resource value: 0x7f070082
			public const int scrollViewContainer = 2131165314;
			
			// aapt resource value: 0x7f07007f
			public const int scrollViewWrapper = 2131165311;
			
			// aapt resource value: 0x7f0700a7
			public const int searchContainer = 2131165351;
			
			// aapt resource value: 0x7f0700c8
			public const int searchWrapper = 2131165384;
			
			// aapt resource value: 0x7f0700f0
			public const int seekBar1 = 2131165424;
			
			// aapt resource value: 0x7f070025
			public const int seekBlue = 2131165221;
			
			// aapt resource value: 0x7f070023
			public const int seekGreen = 2131165219;
			
			// aapt resource value: 0x7f070027
			public const int seekGrey = 2131165223;
			
			// aapt resource value: 0x7f07000a
			public const int seekLR = 2131165194;
			
			// aapt resource value: 0x7f07001b
			public const int seekMover = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int seekRed = 2131165217;
			
			// aapt resource value: 0x7f070087
			public const int slidingDrawer1 = 2131165319;
			
			// aapt resource value: 0x7f07001e
			public const int surfaceCameraView = 2131165214;
			
			// aapt resource value: 0x7f0700f2
			public const int surfaceVideoView = 2131165426;
			
			// aapt resource value: 0x7f070102
			public const int surfaceView1 = 2131165442;
			
			// aapt resource value: 0x7f070103
			public const int textTimeLeft = 2131165443;
			
			// aapt resource value: 0x7f07000c
			public const int textView1 = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int textView2 = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int textView3 = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int textView4 = 2131165206;
			
			// aapt resource value: 0x7f07004d
			public const int txtAuthorName = 2131165261;
			
			// aapt resource value: 0x7f070026
			public const int txtBlueVal = 2131165222;
			
			// aapt resource value: 0x7f07008e
			public const int txtContactName = 2131165326;
			
			// aapt resource value: 0x7f0700c9
			public const int txtContactsSearch = 2131165385;
			
			// aapt resource value: 0x7f07007e
			public const int txtContentPackHeader = 2131165310;
			
			// aapt resource value: 0x7f0700c1
			public const int txtEmailAddress = 2131165377;
			
			// aapt resource value: 0x7f070004
			public const int txtFirstScreenHeader = 2131165188;
			
			// aapt resource value: 0x7f0700a5
			public const int txtGetConnectedLinkedIn = 2131165349;
			
			// aapt resource value: 0x7f070024
			public const int txtGreenVal = 2131165220;
			
			// aapt resource value: 0x7f0700cb
			public const int txtItemTitle = 2131165387;
			
			// aapt resource value: 0x7f07004e
			public const int txtMainMessage = 2131165262;
			
			// aapt resource value: 0x7f070066
			public const int txtPhotoPollMessage = 2131165286;
			
			// aapt resource value: 0x7f070068
			public const int txtPollInfo = 2131165288;
			
			// aapt resource value: 0x7f070075
			public const int txtPollInfo1 = 2131165301;
			
			// aapt resource value: 0x7f070077
			public const int txtPollInfo2 = 2131165303;
			
			// aapt resource value: 0x7f070079
			public const int txtPollInfo3 = 2131165305;
			
			// aapt resource value: 0x7f07007b
			public const int txtPollInfo4 = 2131165307;
			
			// aapt resource value: 0x7f070074
			public const int txtPollMessage = 2131165300;
			
			// aapt resource value: 0x7f070076
			public const int txtPollOption1 = 2131165302;
			
			// aapt resource value: 0x7f070078
			public const int txtPollOption2 = 2131165304;
			
			// aapt resource value: 0x7f07007a
			public const int txtPollOption3 = 2131165306;
			
			// aapt resource value: 0x7f07007c
			public const int txtPollOption4 = 2131165308;
			
			// aapt resource value: 0x7f0700ce
			public const int txtPollText = 2131165390;
			
			// aapt resource value: 0x7f070022
			public const int txtRedVal = 2131165218;
			
			// aapt resource value: 0x7f0700b5
			public const int txtSubHeader2 = 2131165365;
			
			// aapt resource value: 0x7f0700bb
			public const int txtView1 = 2131165371;
			
			// aapt resource value: 0x7f0700bc
			public const int txtView2 = 2131165372;
			
			// aapt resource value: 0x7f070028
			public const int txtWhiteVal = 2131165224;
			
			// aapt resource value: 0x7f0700cd
			public const int webPreview = 2131165389;
			
			// aapt resource value: 0x7f070006
			public const int webView1 = 2131165190;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Animation = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int blank = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CameraTakePicScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ColourPicker = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ComposeAnimationMessage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ComposeAudioMessage = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ComposeMessageContentSelect = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ComposeMessageMain = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ComposePhotoPoll = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ComposePollChoice = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ComposeTextMessage = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ComposeTextPoll = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ContentPack = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ContentPackItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Conversations = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int CreateAnimation = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int EditContact = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int FindContactResults = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int FindContactWCF = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int GetConnectedAuth = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int GetConnectedButtons = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int GetConnectedContacts = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int HomeScreenscrollview = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int LightboxDialog = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int LoginButtons = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int LoginFirstScreen = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int LoginForgottenPass = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int LoginLoL = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int LoginResetPass = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int LoginResetPassConfirm = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int LoginSignupLoL = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int LoginSocialNetwork = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int ManageContactsMain = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int MessageLists = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int ModalPreviewDialog = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int ModalPreviewGIFDialog = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int PhotoPoll = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int previewSoundFX = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int previewTextPoll = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int SelectContacts = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int TextPoll = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int tmpvid = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int video = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int videoMessage = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int ViewContactMessageLists = 2130903084;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050019
			public const int albumsDownloading = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int albumsPleaseWait = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int albumsTitle = 2131034136;
			
			// aapt resource value: 0x7f0500c3
			public const int alertViewEmailEmpty = 2131034307;
			
			// aapt resource value: 0x7f0500c4
			public const int alertViewEmailInvalid = 2131034308;
			
			// aapt resource value: 0x7f0500c9
			public const int alertViewMessageAccessTokenProblem = 2131034313;
			
			// aapt resource value: 0x7f0500cc
			public const int alertViewMessageAccountExists = 2131034316;
			
			// aapt resource value: 0x7f0500c6
			public const int alertViewMessageConnectionProblem = 2131034310;
			
			// aapt resource value: 0x7f0500c5
			public const int alertViewMessageLogoutFailed = 2131034309;
			
			// aapt resource value: 0x7f0500c1
			public const int alertViewMessageNotValidEmailAddress = 2131034305;
			
			// aapt resource value: 0x7f0500ca
			public const int alertViewMessagePasswordEmpty = 2131034314;
			
			// aapt resource value: 0x7f0500bf
			public const int alertViewMessagePasswordFieldsEmpty = 2131034303;
			
			// aapt resource value: 0x7f0500c2
			public const int alertViewTitleFieldEmpty = 2131034306;
			
			// aapt resource value: 0x7f0500c7
			public const int alertViewTitleFirstNameEmpty = 2131034311;
			
			// aapt resource value: 0x7f0500c8
			public const int alertViewTitleLastNameEmpty = 2131034312;
			
			// aapt resource value: 0x7f0500cd
			public const int alertViewTitlePasswordEmpty = 2131034317;
			
			// aapt resource value: 0x7f0500c0
			public const int alertViewTitlePasswordsMismatch = 2131034304;
			
			// aapt resource value: 0x7f0500cb
			public const int alertViewUserCancelledAuth = 2131034315;
			
			// aapt resource value: 0x7f05011c
			public const int animationColsB = 2131034396;
			
			// aapt resource value: 0x7f05011b
			public const int animationColsG = 2131034395;
			
			// aapt resource value: 0x7f05011d
			public const int animationColsO = 2131034397;
			
			// aapt resource value: 0x7f05011a
			public const int animationColsR = 2131034394;
			
			// aapt resource value: 0x7f0500f6
			public const int animationComposeTitle = 2131034358;
			
			// aapt resource value: 0x7f05011e
			public const int animationMessage = 2131034398;
			
			// aapt resource value: 0x7f0500f7
			public const int animationSelectColour = 2131034359;
			
			// aapt resource value: 0x7f050119
			public const int animationTitle = 2131034393;
			
			// aapt resource value: 0x7f050117
			public const int audioTitle = 2131034391;
			
			// aapt resource value: 0x7f050043
			public const int authAccountIDNotToken = 2131034179;
			
			// aapt resource value: 0x7f050048
			public const int authNoDeviceIDSent = 2131034184;
			
			// aapt resource value: 0x7f050044
			public const int authNoToken = 2131034180;
			
			// aapt resource value: 0x7f050046
			public const int authNotAuthenticated = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int authTokenExpired = 2131034183;
			
			// aapt resource value: 0x7f050045
			public const int authTokenLoggedOut = 2131034181;
			
			// aapt resource value: 0x7f0500f5
			public const int chooseFriendsAddingSelectedContacts = 2131034357;
			
			// aapt resource value: 0x7f05008c
			public const int chooseFriendslblMessage = 2131034252;
			
			// aapt resource value: 0x7f050010
			public const int commonAdd = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int commonCancel = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int commonContinue = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int commonDone = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int commonError = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int commonFacebookHeaderView = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int commonGooglePlusHeaderView = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int commonLinkedInHeaderView = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int commonLoggingIn = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int commonOneSec = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int commonSend = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int commonTwitterHeaderView = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int commonYouTubeHeaderView = 2131034124;
			
			// aapt resource value: 0x7f05008b
			public const int composeTextMessagelblMessage = 2131034251;
			
			// aapt resource value: 0x7f050031
			public const int contactsAddingContact = 2131034161;
			
			// aapt resource value: 0x7f05002c
			public const int contactsFinding = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int contactsGetFacebook = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int contactsGetGoogle = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int contactsLinkedIn = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int contactsNoneSelected = 2131034160;
			
			// aapt resource value: 0x7f05002b
			public const int contactsPDTitle = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int contactsRefreshing = 2131034154;
			
			// aapt resource value: 0x7f050032
			public const int contactsSelectContacts = 2131034162;
			
			// aapt resource value: 0x7f050029
			public const int contactsTitle = 2131034153;
			
			// aapt resource value: 0x7f0500fb
			public const int contentCategories = 2131034363;
			
			// aapt resource value: 0x7f0500fa
			public const int contentGrabbingYourPack = 2131034362;
			
			// aapt resource value: 0x7f0500f9
			public const int contentProcessing = 2131034361;
			
			// aapt resource value: 0x7f0500f8
			public const int contentTitle = 2131034360;
			
			// aapt resource value: 0x7f050114
			public const int converseMainTitle = 2131034388;
			
			// aapt resource value: 0x7f050115
			public const int converseShowAllBtn = 2131034389;
			
			// aapt resource value: 0x7f05007d
			public const int createChoose = 2131034237;
			
			// aapt resource value: 0x7f050080
			public const int createCommsError = 2131034240;
			
			// aapt resource value: 0x7f05007b
			public const int createEmail = 2131034235;
			
			// aapt resource value: 0x7f050079
			public const int createFirstName = 2131034233;
			
			// aapt resource value: 0x7f05007c
			public const int createPassword = 2131034236;
			
			// aapt resource value: 0x7f05007f
			public const int createRegister = 2131034239;
			
			// aapt resource value: 0x7f050081
			public const int createSuccess = 2131034241;
			
			// aapt resource value: 0x7f05007a
			public const int createSurname = 2131034234;
			
			// aapt resource value: 0x7f05007e
			public const int createTakePic = 2131034238;
			
			// aapt resource value: 0x7f050078
			public const int createTitle = 2131034232;
			
			// aapt resource value: 0x7f050004
			public const int debugFailToCreateInstall = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int debugPlayingMessage = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int debugPlayingMessageConversations = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int debugPlayingMessagePlayback = 2131034113;
			
			// aapt resource value: 0x7f0500fc
			public const int editContactBlock = 2131034364;
			
			// aapt resource value: 0x7f0500fe
			public const int editContactBlocking = 2131034366;
			
			// aapt resource value: 0x7f050103
			public const int editContactDeleteContact = 2131034371;
			
			// aapt resource value: 0x7f050100
			public const int editContactDeleting = 2131034368;
			
			// aapt resource value: 0x7f050101
			public const int editContactTitle = 2131034369;
			
			// aapt resource value: 0x7f0500fd
			public const int editContactUnblock = 2131034365;
			
			// aapt resource value: 0x7f0500ff
			public const int editContactUnblocking = 2131034367;
			
			// aapt resource value: 0x7f050102
			public const int editContactlblMessage = 2131034370;
			
			// aapt resource value: 0x7f0500b2
			public const int errorAccessTokenError = 2131034290;
			
			// aapt resource value: 0x7f0500be
			public const int errorAudioConvertor = 2131034302;
			
			// aapt resource value: 0x7f050090
			public const int errorAudioProblemTitle = 2131034256;
			
			// aapt resource value: 0x7f0500b8
			public const int errorAuthError = 2131034296;
			
			// aapt resource value: 0x7f0500b0
			public const int errorContentPackFail = 2131034288;
			
			// aapt resource value: 0x7f0500aa
			public const int errorCouldNotGetUserInfoFormat = 2131034282;
			
			// aapt resource value: 0x7f05009d
			public const int errorCouldNotValidateEmailPassword = 2131034269;
			
			// aapt resource value: 0x7f0500af
			public const int errorDownloadFailGeneric = 2131034287;
			
			// aapt resource value: 0x7f0500b1
			public const int errorDownloadPackItems = 2131034289;
			
			// aapt resource value: 0x7f05009b
			public const int errorDownloadingContactList = 2131034267;
			
			// aapt resource value: 0x7f0500a0
			public const int errorDownloadingFriendsFormat = 2131034272;
			
			// aapt resource value: 0x7f0500b7
			public const int errorEditContactsDeleteTitle = 2131034295;
			
			// aapt resource value: 0x7f0500b6
			public const int errorEditContactsSaveTitle = 2131034294;
			
			// aapt resource value: 0x7f050096
			public const int errorEmailInvalid = 2131034262;
			
			// aapt resource value: 0x7f050091
			public const int errorEmptyFilename = 2131034257;
			
			// aapt resource value: 0x7f050093
			public const int errorEmptyURL = 2131034259;
			
			// aapt resource value: 0x7f0500a2
			public const int errorFileTransfer = 2131034274;
			
			// aapt resource value: 0x7f050097
			public const int errorFirstLastTooShort = 2131034263;
			
			// aapt resource value: 0x7f05009c
			public const int errorLoginFailed = 2131034268;
			
			// aapt resource value: 0x7f05008f
			public const int errorMessageSendFail = 2131034255;
			
			// aapt resource value: 0x7f050094
			public const int errorNetFault = 2131034260;
			
			// aapt resource value: 0x7f0500a3
			public const int errorNoImagesTaken = 2131034275;
			
			// aapt resource value: 0x7f05009f
			public const int errorNoPreview = 2131034271;
			
			// aapt resource value: 0x7f0500a6
			public const int errorNotLoggedIn = 2131034278;
			
			// aapt resource value: 0x7f0500b4
			public const int errorPhotoAlbumDownload = 2131034292;
			
			// aapt resource value: 0x7f0500b5
			public const int errorPhotoAlbumInfoDownload = 2131034293;
			
			// aapt resource value: 0x7f050092
			public const int errorPlayingFile = 2131034258;
			
			// aapt resource value: 0x7f050095
			public const int errorPlayingURL = 2131034261;
			
			// aapt resource value: 0x7f0500b3
			public const int errorRefreshFacebookToken = 2131034291;
			
			// aapt resource value: 0x7f0500a4
			public const int errorRefreshingAccessTokenFormat = 2131034276;
			
			// aapt resource value: 0x7f050099
			public const int errorRequestingPasswordResetCode = 2131034265;
			
			// aapt resource value: 0x7f05009a
			public const int errorResettingPassword = 2131034266;
			
			// aapt resource value: 0x7f0500ba
			public const int errorSaveContactMessage = 2131034298;
			
			// aapt resource value: 0x7f0500b9
			public const int errorSaveContactTitle = 2131034297;
			
			// aapt resource value: 0x7f0500a1
			public const int errorSavingContactFormat = 2131034273;
			
			// aapt resource value: 0x7f0500a9
			public const int errorSavingContacts = 2131034281;
			
			// aapt resource value: 0x7f05009e
			public const int errorSearchingContactsByCriteria = 2131034270;
			
			// aapt resource value: 0x7f0500ab
			public const int errorSearchingContactsFailed = 2131034283;
			
			// aapt resource value: 0x7f0500ad
			public const int errorSendingInvitations = 2131034285;
			
			// aapt resource value: 0x7f0500bb
			public const int errorSendingVoiceMessage = 2131034299;
			
			// aapt resource value: 0x7f0500a5
			public const int errorStoreEXIF = 2131034277;
			
			// aapt resource value: 0x7f050098
			public const int errorUnableToSendVerificationCode = 2131034264;
			
			// aapt resource value: 0x7f0500bd
			public const int errorUploadPollingMessage = 2131034301;
			
			// aapt resource value: 0x7f0500bc
			public const int errorUploadingVoiceMessage = 2131034300;
			
			// aapt resource value: 0x7f0500a8
			public const int errorUserCreation = 2131034280;
			
			// aapt resource value: 0x7f0500a7
			public const int errorUserCreationFailed = 2131034279;
			
			// aapt resource value: 0x7f0500ac
			public const int errorUserLoginFailed = 2131034284;
			
			// aapt resource value: 0x7f0500ae
			public const int errorUserLoginProblem = 2131034286;
			
			// aapt resource value: 0x7f050028
			public const int findContactAddingContact = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int findContactNoContactsFound = 2131034151;
			
			// aapt resource value: 0x7f050025
			public const int findContactPhoneNumber = 2131034149;
			
			// aapt resource value: 0x7f050023
			public const int findContactTitle = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int findContactbtnConnect = 2131034150;
			
			// aapt resource value: 0x7f050024
			public const int findContactbtnSearch = 2131034148;
			
			// aapt resource value: 0x7f050042
			public const int forgotNotSent = 2131034178;
			
			// aapt resource value: 0x7f05003f
			public const int forgotPassword = 2131034175;
			
			// aapt resource value: 0x7f05003e
			public const int forgotPasswordMessage = 2131034174;
			
			// aapt resource value: 0x7f050040
			public const int forgotReset = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int forgotSent = 2131034177;
			
			// aapt resource value: 0x7f050037
			public const int getconnectedContinue = 2131034167;
			
			// aapt resource value: 0x7f050034
			public const int getconnectedFB = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int getconnectedGoogle = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int getconnectedLinkedIn = 2131034166;
			
			// aapt resource value: 0x7f050033
			public const int getconnectedTitle = 2131034163;
			
			// aapt resource value: 0x7f05005d
			public const int inviteFacebookPostMessageFormat = 2131034205;
			
			// aapt resource value: 0x7f05005e
			public const int inviteLinkedInPostMessage = 2131034206;
			
			// aapt resource value: 0x7f05005c
			public const int invitePBMessage = 2131034204;
			
			// aapt resource value: 0x7f05005b
			public const int invitePBTitle = 2131034203;
			
			// aapt resource value: 0x7f050077
			public const int loginAuthError = 2131034231;
			
			// aapt resource value: 0x7f050076
			public const int loginAuthGood = 2131034230;
			
			// aapt resource value: 0x7f05006e
			public const int loginCancel = 2131034222;
			
			// aapt resource value: 0x7f05006b
			public const int loginEmail = 2131034219;
			
			// aapt resource value: 0x7f050069
			public const int loginExistingUser = 2131034217;
			
			// aapt resource value: 0x7f05006f
			public const int loginForgotPassword = 2131034223;
			
			// aapt resource value: 0x7f050067
			public const int loginHeader = 2131034215;
			
			// aapt resource value: 0x7f050071
			public const int loginLoggingIn = 2131034225;
			
			// aapt resource value: 0x7f05006d
			public const int loginLogin = 2131034221;
			
			// aapt resource value: 0x7f05006a
			public const int loginNewUser = 2131034218;
			
			// aapt resource value: 0x7f050075
			public const int loginNewUserHeader = 2131034229;
			
			// aapt resource value: 0x7f05006c
			public const int loginPassword = 2131034220;
			
			// aapt resource value: 0x7f050070
			public const int loginRegisteringUser = 2131034224;
			
			// aapt resource value: 0x7f050074
			public const int loginRegistration = 2131034228;
			
			// aapt resource value: 0x7f050072
			public const int loginRegistrationLOL = 2131034226;
			
			// aapt resource value: 0x7f050073
			public const int loginRegistrationMessage = 2131034227;
			
			// aapt resource value: 0x7f050068
			public const int loginSubHeader = 2131034216;
			
			// aapt resource value: 0x7f050039
			public const int logoutMessage = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int logoutOpt1 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int logoutOpt2 = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int logoutOpt3 = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int logoutOutMessage = 2131034173;
			
			// aapt resource value: 0x7f050038
			public const int logoutTitle = 2131034168;
			
			// aapt resource value: 0x7f05001b
			public const int mainTitle = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int manageContactsRetrievingContacts = 2131034142;
			
			// aapt resource value: 0x7f0500d1
			public const int messageAudioClickToRecord = 2131034321;
			
			// aapt resource value: 0x7f0500d4
			public const int messageCreateMessageTitle = 2131034324;
			
			// aapt resource value: 0x7f0500cf
			public const int messageDownloadMessageContent = 2131034319;
			
			// aapt resource value: 0x7f0500d0
			public const int messageDownloadPleaseWait = 2131034320;
			
			// aapt resource value: 0x7f050086
			public const int messageListHeaderViewTitle = 2131034246;
			
			// aapt resource value: 0x7f0500d2
			public const int messageReadMessage = 2131034322;
			
			// aapt resource value: 0x7f050088
			public const int messageRefreshingMessages = 2131034248;
			
			// aapt resource value: 0x7f0500ce
			public const int messageSendingMessage = 2131034318;
			
			// aapt resource value: 0x7f050087
			public const int messageSpeakNow = 2131034247;
			
			// aapt resource value: 0x7f0500d3
			public const int messageStartMessageTitle = 2131034323;
			
			// aapt resource value: 0x7f050089
			public const int messageViewingMessage = 2131034249;
			
			// aapt resource value: 0x7f05008a
			public const int messageViewingPleaseWait = 2131034250;
			
			// aapt resource value: 0x7f05001d
			public const int modalCancel = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int modalOK = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int passwordCancel = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int passwordRecoveryRequestingResetCode = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int passwordRecoverylblMessage = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int passwordReset = 2131034143;
			
			// aapt resource value: 0x7f05008e
			public const int photoNoConnection = 2131034254;
			
			// aapt resource value: 0x7f05008d
			public const int photoTitle = 2131034253;
			
			// aapt resource value: 0x7f0500e4
			public const int pollAddButton = 2131034340;
			
			// aapt resource value: 0x7f0500e1
			public const int pollCancelButton = 2131034337;
			
			// aapt resource value: 0x7f0500e3
			public const int pollCancelConfirm = 2131034339;
			
			// aapt resource value: 0x7f0500e2
			public const int pollCreateButton = 2131034338;
			
			// aapt resource value: 0x7f0500f2
			public const int pollCreateNewPoll = 2131034354;
			
			// aapt resource value: 0x7f0500e0
			public const int pollCreatePollMessage = 2131034336;
			
			// aapt resource value: 0x7f0500df
			public const int pollEditTextTitle = 2131034335;
			
			// aapt resource value: 0x7f0500d5
			public const int pollGettingResults = 2131034325;
			
			// aapt resource value: 0x7f0500ea
			public const int pollOption1 = 2131034346;
			
			// aapt resource value: 0x7f0500eb
			public const int pollOption2 = 2131034347;
			
			// aapt resource value: 0x7f0500ec
			public const int pollOption3 = 2131034348;
			
			// aapt resource value: 0x7f0500ed
			public const int pollOption4 = 2131034349;
			
			// aapt resource value: 0x7f0500d7
			public const int pollPhotoTitle = 2131034327;
			
			// aapt resource value: 0x7f0500d9
			public const int pollPhotoVotePoll = 2131034329;
			
			// aapt resource value: 0x7f0500da
			public const int pollPollResults = 2131034330;
			
			// aapt resource value: 0x7f0500d6
			public const int pollPreviewPhotoPoll = 2131034326;
			
			// aapt resource value: 0x7f0500db
			public const int pollPreviewTextPoll = 2131034331;
			
			// aapt resource value: 0x7f0500d8
			public const int pollPreviewVote = 2131034328;
			
			// aapt resource value: 0x7f0500e5
			public const int pollSendButton = 2131034341;
			
			// aapt resource value: 0x7f0500ee
			public const int pollSubViewDone = 2131034350;
			
			// aapt resource value: 0x7f0500f0
			public const int pollSubViewNumberVotesFormat = 2131034352;
			
			// aapt resource value: 0x7f0500ef
			public const int pollSubViewVotesCast = 2131034351;
			
			// aapt resource value: 0x7f0500dc
			public const int pollTapForPicture = 2131034332;
			
			// aapt resource value: 0x7f0500dd
			public const int pollTapForText = 2131034333;
			
			// aapt resource value: 0x7f0500f1
			public const int pollTapToAdd = 2131034353;
			
			// aapt resource value: 0x7f0500f4
			public const int pollTapToEdit = 2131034356;
			
			// aapt resource value: 0x7f0500de
			public const int pollTextPollTitle = 2131034334;
			
			// aapt resource value: 0x7f0500f3
			public const int pollTextTitle = 2131034355;
			
			// aapt resource value: 0x7f0500e8
			public const int pollUploadPoll = 2131034344;
			
			// aapt resource value: 0x7f0500e6
			public const int pollVoteButton = 2131034342;
			
			// aapt resource value: 0x7f0500e7
			public const int pollVoteDone = 2131034343;
			
			// aapt resource value: 0x7f0500e9
			public const int pollWait = 2131034345;
			
			// aapt resource value: 0x7f050116
			public const int prepareMessage = 2131034390;
			
			// aapt resource value: 0x7f050058
			public const int resetCancel = 2131034200;
			
			// aapt resource value: 0x7f050054
			public const int resetConfirmed = 2131034196;
			
			// aapt resource value: 0x7f050052
			public const int resetEmailAddress = 2131034194;
			
			// aapt resource value: 0x7f050051
			public const int resetInitialMessage = 2131034193;
			
			// aapt resource value: 0x7f050059
			public const int resetLogin = 2131034201;
			
			// aapt resource value: 0x7f050055
			public const int resetPassword = 2131034197;
			
			// aapt resource value: 0x7f050057
			public const int resetReset = 2131034199;
			
			// aapt resource value: 0x7f050053
			public const int resetResetCode = 2131034195;
			
			// aapt resource value: 0x7f05005a
			public const int resetResetting = 2131034202;
			
			// aapt resource value: 0x7f050050
			public const int resetTitle = 2131034192;
			
			// aapt resource value: 0x7f050056
			public const int resetVerifyPassword = 2131034198;
			
			// aapt resource value: 0x7f050109
			public const int selectPreviewBrowseComicon = 2131034377;
			
			// aapt resource value: 0x7f050108
			public const int selectPreviewBrowseComix = 2131034376;
			
			// aapt resource value: 0x7f05010b
			public const int selectPreviewBrowseEmoticon = 2131034379;
			
			// aapt resource value: 0x7f05010a
			public const int selectPreviewBrowseSoundFX = 2131034378;
			
			// aapt resource value: 0x7f05010d
			public const int selectPreviewComiconTitle = 2131034381;
			
			// aapt resource value: 0x7f050110
			public const int selectPreviewComixTitle = 2131034384;
			
			// aapt resource value: 0x7f05010e
			public const int selectPreviewEmoticonTitle = 2131034382;
			
			// aapt resource value: 0x7f050107
			public const int selectPreviewEmoticons = 2131034375;
			
			// aapt resource value: 0x7f05010f
			public const int selectPreviewMessageTitle = 2131034383;
			
			// aapt resource value: 0x7f050112
			public const int selectPreviewPhotoPollTitle = 2131034386;
			
			// aapt resource value: 0x7f050106
			public const int selectPreviewSoundFX = 2131034374;
			
			// aapt resource value: 0x7f050111
			public const int selectPreviewSoundFXTitle = 2131034385;
			
			// aapt resource value: 0x7f05010c
			public const int selectPreviewTap = 2131034380;
			
			// aapt resource value: 0x7f050113
			public const int selectPreviewTextPollTitle = 2131034387;
			
			// aapt resource value: 0x7f050105
			public const int selectPreviewTitleComicon = 2131034373;
			
			// aapt resource value: 0x7f050104
			public const int selectPreviewTitleComix = 2131034372;
			
			// aapt resource value: 0x7f050083
			public const int sendMessageAdd = 2131034243;
			
			// aapt resource value: 0x7f050085
			public const int sendMessageMessageSent = 2131034245;
			
			// aapt resource value: 0x7f050084
			public const int sendMessageSend = 2131034244;
			
			// aapt resource value: 0x7f050082
			public const int sendMessageTextTitle = 2131034242;
			
			// aapt resource value: 0x7f050066
			public const int snusnuFishSticks = 2131034214;
			
			// aapt resource value: 0x7f050063
			public const int verificationCodeFieldEmpty = 2131034211;
			
			// aapt resource value: 0x7f050065
			public const int verificationCodeResetError = 2131034213;
			
			// aapt resource value: 0x7f050064
			public const int verificationCodeSendingVerificationCode = 2131034212;
			
			// aapt resource value: 0x7f050062
			public const int verificationCodeTitle = 2131034210;
			
			// aapt resource value: 0x7f050060
			public const int verificationCodelblEmailFormat = 2131034208;
			
			// aapt resource value: 0x7f05005f
			public const int verificationCodelblMessage = 2131034207;
			
			// aapt resource value: 0x7f050061
			public const int verificationCodelblVerificationCode = 2131034209;
			
			// aapt resource value: 0x7f050049
			public const int videoCloseVideo = 2131034185;
			
			// aapt resource value: 0x7f05004c
			public const int videoErrorTitle = 2131034188;
			
			// aapt resource value: 0x7f05004e
			public const int videoFailToConnect = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int videoFailToPlay = 2131034191;
			
			// aapt resource value: 0x7f05004d
			public const int videoFailToStart = 2131034189;
			
			// aapt resource value: 0x7f05004a
			public const int videoStartRecording = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int videoStopRecording = 2131034187;
			
			// aapt resource value: 0x7f050118
			public const int videoTitle = 2131034392;
			
			// aapt resource value: 0x7f050012
			public const int webAuthFacebook = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int webAuthGoogle = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int webAuthLinkedIn = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int webAuthTwitter = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int webAuthWaitMessage = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int webAuthYouTube = 2131034134;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int dialog_animation = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int lightbox_dialog = 2131099649;
			
			private Style()
			{
			}
		}
	}
}
